services:
  promtail-agent:
    image: grafana/promtail:3.0.0
    command: -config.file=/etc/promtail/promtail-agent.yml -config.expand-env=true
    environment:
      HOST_ALIAS: ${HOST_ALIAS:-unknown-host}
      STAND_NAME: ${STAND_NAME:-stand}
      LOKI_PUSH_URL: ${LOKI_PUSH_URL:-http://192.168.1.29:3100/loki/api/v1/push}
    volumes:
      - ./promtail-agent.yml:/etc/promtail/promtail-agent.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - promtail_agent_positions:/tmp
    restart: unless-stopped

volumes:
  promtail_agent_positions:
